add buttoncompose
soya111/lambda pull request #62
Opened 2023-09-03 15:21 UTC by Toya321

profileflexmessegeにbuttoncomposeを追加しました。
![image](https://github.com/soya111/lambda/assets/142418961/48b2e92d-ee7e-404b-9a78-a52057904b98)

2023-09-03 17:38 UTC, soya111 commented
> profileflexmessegeにbuttoncomposeを追加しました。 ![image](https://user-images.githubusercontent.com/142418961/265273222-48b2e92d-ee7e-404b-9a78-a52057904b98.png)

コミット名（コミットメッセージ）とブランチ名の変更方法は以下の通りです。

1. **コミットメッセージの変更**:
   - 最新のコミットメッセージを変更する場合:
     ```
     git commit --amend -m "新しいコミットメッセージ"
     ```

   - プッシュしてしまった後のコミットメッセージを変更する場合は、変更後に強制プッシュが必要です。しかし、共有リポジトリに強制プッシュすると、他の開発者との歴史が食い違ってしまうので注意が必要です。
     ```
     git push origin <branch-name> --force
     ```

2. **ブランチ名の変更**:
   - ローカルのブランチ名を変更する場合:
     ```
     git branch -m 古いブランチ名 新しいブランチ名
     ```

   - リモートのブランチ名を変更する場合は、新しいブランチ名でプッシュし、古いブランチ名を削除します:
     ```
     git push origin :古いブランチ名
     git push origin 新しいブランチ名
     ```

変更を行う前に、作業内容を確認し、必要に応じてバックアップを取ることをおすすめします。特に共有リポジトリでの変更は他のメンバーとの調整が必要です。

2023-09-04 11:37 UTC, Toya321 commented
profile flex messegeにn期生ラベル(generation label)を追加しました。
![image](https://github.com/soya111/lambda/assets/142418961/7276e6c9-654e-4db7-871f-ef08f77d586a)
![image](https://github.com/soya111/lambda/assets/142418961/d7513bc7-4c94-4666-9e94-88a4e2a35b1d)

また、profcommandにポカで指定すると正しく動作しない現象を修正しました。
![image](https://github.com/soya111/lambda/assets/142418961/4ddbe618-1b19-4d54-bbbf-4698d12432b4)

2023-09-04 12:19 UTC, soya111 requested changes
あと意味のないマージコミットは消しといてください

Gitで最新でないコミットを削除する方法にはいくつかのアプローチがありますが、以下に一般的な方法を示します。注意してください、Gitの履歴を書き換える操作は、共有されているブランチや共同作業中のブランチで行うと他の開発者に混乱をもたらすことがあります。変更前にはバックアップを取るなど、注意を払って作業してください。

1. **リベースを使用してコミットを削除**

   もし、最新でないコミットを削除したい場合、インタラクティブなリベース (`git rebase -i`) を使用できます。例えば、最後から3つ前のコミットを削除したい場合：

   ```bash
   git rebase -i HEAD~3
   ```

   これによりテキストエディタが開きます。削除したいコミットの行の `pick` を `drop` に変更（あるいはその行を完全に削除）して、エディタを保存して閉じます。これにより指定したコミットが削除されます。

2. **`git reset` と `git cherry-pick` を使用して履歴を書き換える**

   これはもう少し手動の方法です。必要なコミットのみを選択して新しいコミット履歴を作成します。

   1. まず、最新の状態をバックアップブランチに保存しておきます。
      
      ```bash
      git branch backup-branch
      ```

   2. 次に、削除したいコミットの一つ前までブランチをリセットします。
      
      ```bash
      git reset --hard [削除したいコミットの一つ前のコミットハッシュ]
      ```

   3. そして、削除したくないコミットを個別に選択して適用します。
      
      ```bash
      git cherry-pick [適用したいコミットハッシュ]
      ```

   この方法は、特定のコミットのみを選択して新しいコミット履歴を作成したい場合に適しています。

いずれの方法も履歴を書き換えるため、これらの変更をリモートリポジトリにプッシュする際には `git push origin branch-name --force` のように `--force` オプションを使用して強制的にプッシュする必要があります。ただし、強制プッシュは注意が必要ですので、共同作業者との調整が必要です。

2023-09-04 12:19 UTC, soya111 commented on pkg/profile/hinatazaka_profile.go
> +										},
メッセージアクションでもいいのですが、postbackのほうにしてほしいですね

2023-09-04 12:19 UTC, soya111 commented on app/webhook/command_handler.go
>  	selection, pokaerr := profile.GetProfileSelection(member)
pokaerrではなくerrにしたほうがいいとおもいます
pokaerrでないエラーが返る可能性もあるため

2023-09-04 12:19 UTC, soya111 commented on pkg/profile/hinatazaka_profile.go
> +				Text:    model.MemberToGenerationMap[name] + "期生",
呼び出し元でmemberが存在することが保証されていない場合、panicする気がします

2023-09-04 14:39 UTC, Toya321 commented on pkg/profile/hinatazaka_profile.go
> +				Text:    model.MemberToGenerationMap[name] + "期生",
![image](https://github.com/soya111/lambda/assets/142418961/96c48e41-fc83-49b3-a937-e1e9979b3b75)
ここでメンバーが存在していることが保証されている気がしますが、この場合はセーフ？

2023-09-04 15:42 UTC, soya111 commented on pkg/profile/hinatazaka_profile.go
> +				Text:    model.MemberToGenerationMap[name] + "期生",
じゃあ許す

あと画像ではなくリンクを貼りましょう

2023-09-04 16:46 UTC, Toya321 commented on pkg/profile/hinatazaka_profile.go
> +										},
postbackactionに変更しました

2023-09-04 16:46 UTC, Toya321 commented on app/webhook/command_handler.go
>  	selection, pokaerr := profile.GetProfileSelection(member)
変更しました

2023-09-04 16:49 UTC, Toya321 commented
ラベル作成を一般化したcreatelebelcomponentを追加しました。
引数として表示テキスト、テキスト色、背景色を指定します。
また、ラベルの幅はテキストの長さにできるだけアジャストできるようにしています。

2023-09-05 02:34 UTC, soya111 commented on pkg/profile/hinatazaka_profile.go
> +										},
現状の実装で動かないと思います

2023-09-05 10:46 UTC, Toya321 commented on pkg/profile/hinatazaka_profile.go
> +										},
![image](https://github.com/soya111/lambda/assets/142418961/9c25c0fc-6b04-47cd-ab61-09a34ff41dc9)
できるけども

2023-09-05 10:57 UTC, soya111 commented on pkg/profile/hinatazaka_profile.go
> +										},
ポストバックアクションに変更してほしいです

2023-09-05 11:56 UTC, Toya321 commented
postbackactionを修正しました

2023-09-05 16:03 UTC, soya111 commented on app/webhook/command_handler.go
> +		return fmt.Errorf("ProfCommand.Execute: %w", err)
サーバーサイドのエラーではないのでエラーを返さないでください
普通にreturnしといてください

2023-09-05 16:06 UTC, soya111 commented on pkg/profile/hinatazaka_profile.go
https://github.com/soya111/lambda/pull/62/files#diff-c4c3b4083d709d0c847540e4d4078539825f05c3bf11c4b449a7951bf76fb136R30

こちらですが、member.goに移設してください

2023-09-06 10:32 UTC, soya111 commented on app/webhook/command_handler.go
>  		if err := c.bot.ReplyTextMessages(context.TODO(), event.ReplyToken, fmt.Sprintf("%sは存在しません。", member)); err != nil {
これやこれと同等のところもctxに変えておいてください

2023-09-06 10:32 UTC, soya111 commented on pkg/model/member.go
> +	"渡邉美穂":  "2",
このあたりバグらないかローカルで確認してください

2023-09-06 15:09 UTC, Toya321 commented on app/webhook/command_handler.go
>  		if err := c.bot.ReplyTextMessages(context.TODO(), event.ReplyToken, fmt.Sprintf("%sは存在しません。", member)); err != nil {
ctxに置換しました

2023-09-06 15:09 UTC, Toya321 commented on pkg/model/member.go
> +	"渡邉美穂":  "2",
卒業メンバーの取り扱いを追加しました。

2023-09-06 15:11 UTC, Toya321 commented
卒業メンバーを判定するIsGrad()を作成し、卒業メンバーの取り扱いを追加しました。

2023-09-06 15:54 UTC, Toya321 commented on pkg/model/member.go
> +	"渡邉美穂":  "2",
別のブランチに移動しました

2023-09-06 16:09 UTC, soya111 commented
<img src="https://images.lgtmgen.org/616e3212-1613-4f16-92c7-ab64e5c696fc" alt="LGTM" />

2023-09-06 16:11 UTC, merged